# Generated by Django 2.1.7 on 2020-03-08 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0002_output'),
    ]

    operations = [
        migrations.RenameField(
            model_name='output',
            old_name='voilations',
            new_name='violations',
        ),
    ]
