# Generated by Django 2.1.7 on 2020-03-09 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0003_auto_20200308_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='output',
            name='active_card',
        ),
        migrations.RemoveField(
            model_name='output',
            name='available_limit',
        ),
        migrations.AddField(
            model_name='output',
            name='account',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='case.Account'),
            preserve_default=False,
        ),
    ]
