# Generated by Django 2.1.7 on 2020-03-09 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0005_auto_20200309_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='output',
            name='account',
        ),
        migrations.RemoveField(
            model_name='output',
            name='id',
        ),
        migrations.AddField(
            model_name='output',
            name='account_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='case.Account'),
            preserve_default=False,
        ),
    ]
